### ISSUE TITLE
Demo app instructions URL is wrong

### ISSUE THREAD

**Issue by dukeyin** [isisaddons/isis-wicket-wizard#2]
On https://github.com/isisaddons/isis-wicket-wizard/blob/master/README.md#how-to-run-the-demo-app it says to clone `https://github.com/isisaddons/isis-module-wizard.git` which does not exist... is this intentional?

**Comment by danhaywood** [comment]
Fixed ... should've been isis-wicket-wizard.git

NB: this component is work-in-progress.  Actually, it's not been touched in quite a while, not sure when/if will resurrect.
